name: Convert Markdown to HTML

on:
  push:
    branches:
      - main
    paths:
      - tilt-pi-monitor-stack-docker-guide.md
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install markdown-to-html-cli
        run: npm install -g markdown-to-html-cli

      - name: Convert Markdown to HTML
        run: |
          markdown-to-html --input=tilt-pi-monitor-stack-docker-guide.md --output=tilt-pi-monitor-stack-docker-guide.html

      - name: Debug Git
        run: |
          git status
          git remote -v
          git branch

      - name: Commit and push changes
        run: |
          git pull --rebase
          git add tilt-pi-monitor-stack-docker-guide.html
          git commit -m "feat: add or update HTML version of the guide"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
