name: Convert Markdown to HTML

on:
  push:
    paths:
      - "tilt-pi-monitor-stack-docker-guide.md" # Trigger only when this file changes
  workflow_dispatch: # Allow manual triggering of the workflow

jobs:
  convert-markdown:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install markdown-to-html tool
        run: pip install markdown

      - name: Convert Markdown to HTML
        run: |
          python -c "
          import markdown
          with open('tilt-pi-monitor-stack-docker-guide.md', 'r') as md_file:
              content = md_file.read()
          html_content = markdown.markdown(content)
          with open('tilt-pi-monitor-stack-docker-guide.html', 'w') as html_file:
              html_file.write(html_content)
          "

      - name: Commit and Push HTML File
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add tilt-pi-monitor-stack-docker-guide.html
          git commit -m "Convert markdown to HTML"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "Add HTML version of markdown guide"
          branch: "convert-md-to-html"
          title: "Add converted HTML file"
          body: |
            This pull request adds the HTML version of `tilt-pi-monitor-stack-docker-guide.md`.
