name: Convert Markdown to HTML

on:
  push:
    paths:
      - 'tilt-pi-monitor-stack-docker-guide.md'
  workflow_dispatch:  # Allows manual triggering

jobs:
  render-markdown:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Convert Markdown to HTML via API
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          CONTENT=$(cat tilt-pi-monitor-stack-docker-guide.md)
          RESPONSE=$(curl -s -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Content-Type: application/json" \
            -d "{\"text\": \"$CONTENT\", \"mode\": \"gfm\"}" \
            https://api.github.com/markdown)
          echo "$RESPONSE" > tilt-pi-monitor-stack-docker-guide.html

      - name: Create New Branch
        run: |
          git checkout -b update-html-$(date +%Y%m%d%H%M%S)

      - name: Commit and Push HTML
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add tilt-pi-monitor-stack-docker-guide.html
          git commit -m "feat: convert guide to html"
          git push origin HEAD
