name: Convert Markdown to HTML and Create PR

on:
  push:
    branches:
      - main
    paths:
      - tilt-pi-monitor-stack-docker-guide.md
  workflow_dispatch:

permissions:
  contents: write  # Allow writing to repository contents

jobs:
  convert:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install markdown-to-html-cli
        run: npm install -g markdown-to-html-cli

      - name: Convert Markdown to HTML
        run: |
          markdown-to-html --input=tilt-pi-monitor-stack-docker-guide.md --output=tilt-pi-monitor-stack-docker-guide.html

      - name: Configure Git Identity
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Create and Switch to New Branch
        run: |
          git checkout -b update-html-${{ github.run_id }}  # Use a unique branch name based on the workflow run ID
          git add tilt-pi-monitor-stack-docker-guide.html
          git commit -m "feat: add or update HTML version of the guide"

      - name: Push Changes to New Branch
        run: |
          git push -u origin update-html-${{ github.run_id }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: update-html-${{ github.run_id }}
          title: "feat: add or update HTML version of the guide"
          body: |
            This pull request contains the latest HTML conversion of the guide for review.
            - Workflow Run ID: ${{ github.run_id }}
